config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#homepage'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :meals, only: [:index, :show, :new, :create]
  resources :lines, only: [:create, :update]
  resources :orders, only: [:new, :show, :update] do
  resources :reviews, only: [ :new, :create ]
  end
  get '/settings', to: 'pages#settings'
  get '/home', to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard'

  resources :charges, only: [:new, :create]


  resources :chatrooms, only: :show do
    resources :messages, only: [ :new, :create ]
  end


  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :meals, only: [ :index, :show, :update, :create, :destroy ]
    end
  end
end

app/views/shared/_checkout_modal.html.erb
<div id="checkout" class="overlay">
  <!-- Button to close the overlay navigation -->
  <div class="close-btn">
    <a href="javascript:void(0)" id="close-btn">&times;</a>
  </div>
  <!-- Overlay content -->
  <div class="overlay-content">
    <div class="container">
      <h1><%= @chef.full_name %> also cooks </h1>
      <% @other_courses.each do |meal| %>
        <div class="flex-modal">
          <div class="card-suggestion transparent" id="other-course-meal-id-<%= meal.id%>" style="background-image: url(<%= cl_image_path meal.photo.key, height: 320, width: 300, crop: :fill %>);">
            <div class="card-suggestion-infos">
              <div>
                <%= link_to meal_path(meal, quantity: params[:quantity]) do %>
                <h2><strong><%= meal.name[0..15] %></strong></h2>
                <p><%= meal.price_cents.fdiv(100) %>€</p>
                <% end %>
              </div>
              <div class="card-suggestion-footer">
                <div><div class="tag-show-card"><p><%= meal.courses.first.name %></p></div></div>
                <div class="meal-card-action">
                <%#  <i class="fas fa-shopping-basket"></i>%>
                  <a href="#" class="add-to-cart" data-meal-id=<%= meal.id %>>+</a>
                  <a href="#" class="meal-added-to-cart" data-meal-id=<%= meal.id %>>Added</a>
                </div>
              </div>
            </div>
          </div>
              </div>
        <% end %>
          <%= simple_form_for Line.new do |f| %>
            <center><div class="btn-order-checkout">
              <%= f.button :submit, "Go to checkout" %>
            </div></center>
            <%= f.input :meal, :as => :hidden, :input_html => { :value => @meal.id } %>
            <% @other_courses.each do |meal| %>
              <%= f.input :meal ,:as => :hidden, input_html: { name: "other_meal_#{meal.id}", id: "other_meal_added_to_basket_#{meal.id}", class: "other_meal_added_to_basket"} %>
            <% end %>

            <%# <%= l.input :quantity ,:as => :hidden, input_html: { name: "line_#{line.id}", id: "quantity_input_line_#{line.id}", class: "quantity-input"} %>
          <% end %>
    </div>
  </div>
</div>

<a href="javascript:void(0)" id="open-btn">Yummi</a>

app/views/shared/_filter_form.html.erb
<div id="myNav" class="overlay">

  <!-- Button to close the overlay navigation -->
  <a href="javascript:void(0)" id="close-btn">&times;</a>

  <!-- Overlay content -->
  <div class="overlay-content">

  <div class="container color-white">

    <%= form_tag meals_path, method: :get do %>

    <legend id="title-filters" class="pt-0">What are you Yumming for?</legend>

      <%= text_field_tag :query,
        params[:query],
        class: "form-control mb-3 form-control-bigger",
        placeholder: "Type a dish"
      %>

      <%= text_field_tag :chef,
        params[:chef],
        class: "form-control mb-3 form-control-bigger",
        placeholder: "Type a chef"
      %>

      <%= text_field_tag :day,
        params[:day],
        class: "form-control datepicker mb-3 form-control-bigger",
        placeholder: "Type a date"
      %>
      <p class="mb-1">Add a price range:</p>
      <%= text_field_tag :price,
        params[:price],
        class: "js-range-slider-price color-orange mb-5"
      %>
      <p class="mb-1">Add an address:</p>
      <%= text_field_tag :home_address,
        params[:home_address],
        class: "form-control mb-3 form-control-bigger",
        id:"address",
        placeholder: "What is your delivery address?"
      %>

      <ul class= "results">
      </ul>
      <p class="mb-1">Maximum distance:</p>
      <%= text_field_tag :distance,
        params[:distance],
        class: "js-range-slider-radius mb-3"
      %>

      <legend class="pt-0">What's your mood like?</legend>
      <% @cuisines.each do |cuisine| %>
        <div class="tag-item">
          <%= check_box_tag "cuisine[]", cuisine,
          params[:cuisine].present? && params[:cuisine].include?(cuisine),
            class: 'form-check-input check_boxes optional tag-selector',
            id: "cuisine-#{cuisine}" %>
          <label class="form-check-label collection_check_boxes" for="cuisine-<%= cuisine %>"><%= cuisine %></label>
        </div>
      <% end %>

    <legend class=" pt-0">Choose your course:</legend>
      <% @courses.each do |course| %>
        <div class="tag-item">
          <%= check_box_tag "course[]", course.id,
          params[:course].present? && params[:course].include?(course.id.to_s),
            class: 'form-check-input check_boxes optional tag-selector',
            id: "course-#{course.id}" %>
          <label class="form-check-label collection_check_boxes" for="course-<%= course.id %>"><%= course.name %></label>
        </div>
      <% end %>
      <br>

      <%= submit_tag "Search", class: "btn btn-primary mt-5 mb-5 btn-home" %>
      <br>
    <% end %>
   </div>
   </div>
</div>


  <!-- <input type="text" class="js-range-slider" name="my_range" value="" /> -->



<script>
  $(".js-range-slider-price").ionRangeSlider({
      type: "double",
      skin: "round",
      min: <%= Meal.minimum(:price_cents) / 100 %>,
      max: <%= Meal.maximum(:price_cents) / 100 %> ,
      from: <%= params[:price] ? params[:price].split(';').first.to_i : Meal.minimum(:price_cents) / 100 %>,
      to: <%= params[:price] ? params[:price].split(';').last.to_i : Meal.maximum(:price_cents) / 100 %>,
      prefix: "€"
    });

  $(".js-range-slider-radius").ionRangeSlider({
      skin: "round",
      min: 0,
      max: 10 ,
      from: <%= params[:distance] ? params[:distance].to_i : 10 %>,
      postfix: "km"
    });
</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_home-enter.html.erb
  <%= form_tag home_path, method: :get do %>
    <center><%= submit_tag "Yummi!", class: "btn btn-primary btn-home-page" %></center>
  <% end %>

  <style>
    .btn-home-page {
      font-size: 20px;
      width: 150px;
      padding: 0px;
      margin: 0px;
    }
  </style>

app/views/shared/_home_form.html.erb
<%= form_tag meals_path, method: :get do %>

  <p class="mb-1 p-homepage">Where?</p>
  <%= text_field_tag :home_address,
    params[:home_address] || current_user&.home_address || session[:home_address] || "Parvis Notre-Dame — Place Jean-Paul II, Parvis Notre-Dame, Paris, 75004, France",
    class: "form-control mb-4 form-control-bigger",
    id:"address",
    autocomplete: "off"
  %>

  <ul class= "results">
  </ul>

  <p class="mb-1 p-homepage">When?</p>
  <%= text_field_tag :day,
    params[:day] || "#{1.day.from_now.to_date} 20:00",
    class: "form-control flatpickr datepicker search-form form-control-bigger",
    autocomplete: "off"
  %>
  <br>
  <center><%= submit_tag "Let's get yummi food!", class: "btn-home" %></center>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar">

  <%= link_to home_path do %>
    <% if params[:controller] == 'pages' && params[:action] == 'home'%>
      <div class="navbar__item">
        <span class="navbar__icon">
          <%= image_tag 'homeorange.svg' %>
        </span>
      </div>
    <% else %>
      <div class="navbar__item">
        <span class="navbar__icon">
          <%= image_tag 'home.svg' %>
        </span>
      </div>
    <% end %>
  <% end %>


  <%= link_to meals_path do %>
    <% if params[:controller] == 'meals' && params[:action] == 'index'%>
      <div class="navbar__item">
        <span class="navbar__icon">
          <%= image_tag 'searchorange.svg' %>
        </span>
      </div>
    <% else %>
      <div class="navbar__item">
        <span class="navbar__icon">
          <%= image_tag 'search.svg' %>
        </span>
      </div>
    <% end %>
  <% end %>


  <%= link_to dashboard_path do  %>
    <% if params[:controller] == 'pages' && params[:action] == 'dashboard'%>
      <div class="navbar__item">
        <span class="navbar__icon">
            <%= image_tag 'userorange.svg' %>
        </span>
      </div>
    <% else %>
      <div class="navbar__item">
        <span class="navbar__icon">
          <%= image_tag 'user.svg' %>
        </span>
      </div>
    <% end %>
  <% end %>

</div>

app/views/shared/_search_form.html.erb
<%= form_tag meals_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "What would make you feel Yummi?"
  %>

  <%= text_field_tag :day,
    params[:day],
    class: "form-control datepicker",
    placeholder: "When?"
  %>

     <%= text_field_tag :home_address,
    params[:home_address],
    class: "form-control",
    placeholder: "What is your home address"
  %>

  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

<%= console  %>