config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#homepage'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :meals, only: [:index, :show, :new, :create]
  resources :lines, only: [:create, :update]
  resources :orders, only: [:new, :show, :update] do
  resources :reviews, only: [ :new, :create ]
  end
  get '/settings', to: 'pages#settings'
  get '/home', to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard'

  resources :charges, only: [:new, :create]


  resources :chatrooms, only: :show do
    resources :messages, only: [ :new, :create ]
  end


  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :meals, only: [ :index, :show, :update, :create, :destroy ]
    end
  end
end

app/views/pages/dashboard.html.erb
  <ul class="list-inline tabs-underlined">
   <li>
     <%= link_to "Orders", dashboard_path, class: "tab-underlined #{"active" if params[:action] == "dashboard"}" %>
   </li>
   <li>
     <%= link_to "Messages", "#", class: "tab-underlined" %>
   </li>
   <li>
     <%= link_to "  Settings", settings_path , class: "tab-underlined" %>
   </li>
 </ul>
<div class= "container" >
  <div class ="container-order">

    <%# <div class="card-product-order"> %>
      <%# <%= cl_image_tag @meal.photo.key %>
      <%# <div class="card-product-order-infos"> %>
        <%# <p><strong>Product name</strong></p> %>
        <%# <p>Color: Black, Size: M, Qty: 1</p> %>
      <%# </div> %>
      <%# <p>$49.00</p> %>
    <%# </div> %>
    <div class="order-cards">
      <% @orders.each do |order| %>
        <% if order.status != "In_progress" %>
          <div class="order-card">
            <div class="order-card-head">
              <div class="order-card-head-infos">
                <div class="order-card-head-infos-left">
                  <div class="container-dashboard-order">
                    <p><%= order.status %></p>
                    <p><%= order.price_cents.fdiv(100) if order.price_cents %>€</p>
                    <p><%= order.random_delivery_date %></p>
                  </div>
                </div>
  <!--               <div class="order-card-head-infos-right">
                  <i class="far fa-comments"></i>
                </div> -->

                <%= link_to chatroom_path(order.chatroom) do  %>
                  <div class="order-card-head-infos-right">
                    <i class="far fa-comments"></i>
                  </div>
                <% end %>

              </div>
                  <% if order.review %>
                    <p>" <%= order.review.content %> " - <%= order.review.rating %> / 5</p>
                  <% else %>
                    <div class="dashboard-review">
                      <a id="review-link" data-toggle="modal" data-target="#exampleModal" class="btn btn-primary">Leave a review</a>
                    </div>
                  <% end %>
                  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-footer">
                      <div class="modal-body">
                        <%= render "reviews/new", order: order %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
                <div class="order-card-detail-btn" >
                  <center><a href="" data-order-id="<%= order.id %>">
                    <i class="fas fa-chevron-down"></i>
                  </a></center>
                </div>
<!-- Expandable details start-->
              <div class="order-card-lines" id="order-lines-<%= order.id %>">
                  <% order.lines.each do |line| %>
                    <div class="order-line">
                      <div class="order-line-left">
                        <div class="flex-quantity">
                          <p><%= line.quantity %></p>
                        </div>
                        <p><%= line.meal.name %></p>
                      </div>
                      <div class="order-line-right">
                        <p><%= line.meal.price_cents.fdiv(100).round(2) %> €</p>
                      </div>
                    </div>
                  <% end %>
                <div class="order-card-details-btn">
                  <P>Total : <%= order.total_before_checkout.fdiv(100).round(2) %> €</P>
              </div>
                <div class="order-card-details-bottom">

                </div>
  <!-- Expandable details start-->
                <div class="order-card-lines" id="order-lines-<%= order.id %>">
                    <% order.lines.each do |line| %>
                      <div class="order-line">
                        <div class="order-line-left">
                          <div class="flex-quantity">
                            <p><%= line.quantity %></p>
                          </div>
                          <p><%= line.meal.name %></p>
                        </div>
                        <div class="order-line-right">
                          <p><%= line.meal.price_cents.fdiv(100).round(2) %> €</p>
                        </div>
                      </div>
                    <% end %>
                  <div class="order-card-details-expanded-bottom">
                    <P>Total : <%= order.total_before_checkout.fdiv(100).round(2) %> €</P>
                    <a href="#" data-order-id="<%= order.id %>">
                      <i class="far fa-minus-square"></i>
                    </a>
                  </div>
                </div>
  <!-- Expandable details end-->
  <!-- Modal -->

            </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <%# <footer class="mt-3">
      <ul class="flex flex-column">
        <li class="d-flex justify-content-between"><i>Subtotal</i> <i>$98.00</i></li>
        <li class="d-flex justify-content-between"><i>Tax</i> <i>$10.00</i></li>
        <li class="d-flex justify-content-between"><i>Delivery</i> <i>Free</i></li>
        <li class="d-flex justify-content-between"><i>Total</i> <i>$108.00</i></li>
      </ul>
    </footer> %>

  </div>
</div>

app/views/pages/home-page.html.erb
<div class="home-page">

  <br><br><br><br><br><br><br><br><br>
  <div class="text-height">
    <h2><span id="banner-typed-text"></span></h2>
  </div>

  <br>

  <div class="home-page-btn">

    <%= render 'shared/home-enter' %>
    
  </div>
 
</div>
    

app/views/pages/home.html.erb
<div class="banner">
  <h2>Eat local food, prepared with love</h2>
  <div class="search-bar">
    <center><%= render 'shared/home_form' %></center>
  </div>
</div>

<div class="titles">
  <h3>Moment offers </h3>
  <%= link_to "See all", meals_path, id: 'link-to'  %>
</div>

<div class="card-flex">

  <ul>
    <% @meals.each do |meal| %>
    <li>
      <div class="card-suggestion-home" style="background-image: url(<%= cl_image_path meal.photo.key, height: 320, width: 300, crop: :fill %>);">
        <div class="card-suggestion-infos-home">
          <%= link_to meal_path(meal), id: 'link' do %>
            <div class="display-flex-card">
              <div class="display-column">
                <h2 id="margin-top"><strong><%= meal.name[0..25] %></strong></h2>
                <div><div class="tag-show-card"><p><%= meal.cuisine %></p></div></div>
              </div>
              <div class="display-column">
                <% if meal.user.rating_average != nil %>
                    <div class="flex-reviews">
                      <h3 class="width-auto"><%= meal.user.full_name %></h3>
                      <%= image_tag 'star.svg' %>
                      <h3 id="flex-grow"><%= number_to_human  meal.user.rating_average %>/5</h3>
                    </div>
                  <% else %>
                    <h3><%= meal.user.full_name %></h3>
                  <% end %>
                <h2 class="price-tag"><%= meal.price_cents.fdiv(100) %>€</h2>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
</div>

app/views/pages/homepage.html.erb
<div class="home-page">

  <%= image_tag 'YummiV4.png'%>

  <br>

  <div class="home-page-btn">

    <%= render 'shared/home-enter' %>

  </div>

</div>

app/views/pages/settings.html.erb
<%= link_to 'Log_out', destroy_user_session_path, :method => :delete %>

app/views/pages/temporary.html.erb
<form>
      <input type="text" placeholder="add an address" id= "address" style= "width: 50vw; padding: 10px; border-radius: 20px ">
      <!-- <input type="submit" value="Submit" id= "submit-button"> -->
  </form>

    <ul id="results">
    </ul>

  <%= text_field_tag :price,
    params[:price],
    class: "js-range-slider",
    placeholder: "What price for each invitee ?"
  %>

  <!-- <input type="text" class="js-range-slider" name="my_range" value="" /> -->

  <script>
    $(".js-range-slider").ionRangeSlider({
        type: "double",
        skin: "round",
        min: 0,
        max: 1000,
        from: 200,
        to: 500,
        prefix: "€"
      });
  </script>

<style>

  #results {
      width: 50vw;
      list-style: none;
      padding: 0;
  }

  #results li:hover {
    /*when hovering an item:*/
    background-color: #e9e9e9;
  }

  #results li {
    border-radius: 20px;
    width: 50vw;
    padding: 10px;
    cursor: pointer;
    background-color: #fff;
    border-bottom: 1px solid #d4d4d4;
  }

  .autocomplete-active {
    /*when navigating through the items using the arrow keys:*/
    background-color: DodgerBlue !important;
    color: #ffffff;
  }

</style>