config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#homepage'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :meals, only: [:index, :show, :new, :create]
  resources :lines, only: [:create, :update]
  resources :orders, only: [:new, :show, :update] do
  resources :reviews, only: [ :new, :create ]
  end
  get '/settings', to: 'pages#settings'
  get '/home', to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard'

  resources :charges, only: [:new, :create]


  resources :chatrooms, only: :show do
    resources :messages, only: [ :new, :create ]
  end


  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :meals, only: [ :index, :show, :update, :create, :destroy ]
    end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create
    raise
    # Amount in cents
    @order = Order.find(params[:OrderId])
    @user = current_user
    @amount = @order.total_before_checkout

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'eur',
    })

    # Chatroom.create(order_id: @order.id, user_id: @user.id, cook_id: @order.lines.first.meal.user.id)
    session[:order_id] = nil
    redirect_to dashboard_path
    @order.status = "Paid"


  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>
  <!-- <input name="OrderId" type="hidden" value="<%= @order.id %>"> -->

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%= Rails.configuration.stripe[:publishable_key] %>" data-description="A month's subscription" data-amount="500" data-currency="eur" data-locale="auto"></script>
<% end %>